In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix, accuracy_score

In [3]:
df = pd.read_csv('Social_Network_Ads.csv')
x = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

In [14]:
x_train , x_test, y_train, y_test = train_test_split(x,y, test_size=0.25,random_state=0)


In [15]:
print(x_train)

[[    28  59000]
 [    40  57000]
 [    59 143000]
 [    57  26000]
 [    52  38000]
 [    47 113000]
 [    53 143000]
 [    35  27000]
 [    58 101000]
 [    45  45000]
 [    23  82000]
 [    46  23000]
 [    42  65000]
 [    28  84000]
 [    38  59000]
 [    26  84000]
 [    29  28000]
 [    37  71000]
 [    22  55000]
 [    48  35000]
 [    49  28000]
 [    38  65000]
 [    27  17000]
 [    46  28000]
 [    48 141000]
 [    26  17000]
 [    35  97000]
 [    39  59000]
 [    24  27000]
 [    32  18000]
 [    46  88000]
 [    35  58000]
 [    56  60000]
 [    47  34000]
 [    40  72000]
 [    32 100000]
 [    19  21000]
 [    25  90000]
 [    35  88000]
 [    28  32000]
 [    50  20000]
 [    40  59000]
 [    50  44000]
 [    35  72000]
 [    40 142000]
 [    46  32000]
 [    39  71000]
 [    20  74000]
 [    29  75000]
 [    31  76000]
 [    47  25000]
 [    40  61000]
 [    34 112000]
 [    38  80000]
 [    42  75000]
 [    47  47000]
 [    39  75000]
 [    19  25000]
 [    37  8000

In [16]:
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)


In [17]:
print(x_train)

[[-0.95215868 -0.22005819]
 [ 0.21613418 -0.27905503]
 [ 2.06593121  2.25780886]
 [ 1.87121573 -1.19350596]
 [ 1.38442704 -0.83952496]
 [ 0.89763835  1.37285634]
 [ 1.48178478  2.25780886]
 [-0.27065451 -1.16400755]
 [ 1.96857347  1.01887533]
 [ 0.70292287 -0.63303603]
 [-1.43894737  0.4584054 ]
 [ 0.80028061 -1.28200121]
 [ 0.41084966 -0.04306769]
 [-0.95215868  0.51740224]
 [ 0.0214187  -0.22005819]
 [-1.14687416  0.51740224]
 [-0.85480094 -1.13450913]
 [-0.07593904  0.13392281]
 [-1.53630511 -0.33805186]
 [ 0.99499609 -0.92802021]
 [ 1.09235383 -1.13450913]
 [ 0.0214187  -0.04306769]
 [-1.04951642 -1.45899172]
 [ 0.80028061 -1.13450913]
 [ 0.99499609  2.19881202]
 [-1.14687416 -1.45899172]
 [-0.27065451  0.90088166]
 [ 0.11877644 -0.22005819]
 [-1.34158964 -1.16400755]
 [-0.56272773 -1.4294933 ]
 [ 0.80028061  0.63539591]
 [-0.27065451 -0.24955661]
 [ 1.77385799 -0.19055978]
 [ 0.89763835 -0.95751862]
 [ 0.21613418  0.16342123]
 [-0.56272773  0.98937692]
 [-1.82837833 -1.34099805]
 

In [18]:
clf = SVC(kernel = 'linear', random_state=0)
clf.fit(x_train,y_train)

SVC(kernel='linear', random_state=0)

In [19]:
y_pred = clf.predict(x_test)
print(y_pred)

[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0
 0 0 0 0 0 0 0 1 0 0 1 0 1 1 0 0 0 1 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0
 0 0 0 0 1 1 1 1 0 0 1 0 0 1 0 0 0 1 0 0 0 0 0 0 1 1 0 0 0 0 1 1 0 0 0 0 0
 0 0 0 1 1 1 0 1 1 0 1 0 1 0 0 0 1 0 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 1 0 1
 1 0 0 0 0 0 1 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 0 0 0 0 0
 1 0 0 1 1 0 0 1 0 0 0 1 1 1 0]


In [20]:
print(y_test)

[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 1 1 0 0 0 0
 0 0 1 0 0 0 0 1 0 0 1 0 1 1 0 0 0 1 1 0 0 1 0 0 1 0 1 0 1 0 0 0 0 1 0 0 1
 0 0 0 0 1 1 1 0 0 0 1 1 0 1 1 0 0 1 0 0 0 1 0 1 1 1 0 1 0 1 1 1 0 0 0 0 0
 0 1 1 1 0 1 0 0 1 0 1 0 1 0 0 1 1 1 1 0 1 0 1 0 0 1 0 0 1 0 0 0 0 0 1 1 1
 1 0 0 0 1 0 1 0 1 0 0 1 0 0 0 1 0 0 0 1 1 0 0 1 0 1 1 1 0 0 1 1 0 0 1 1 0
 1 0 0 1 1 0 1 1 1 0 0 0 0 0 1]


In [21]:
cm = confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[116   7]
 [ 32  45]]


0.805